// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_stream

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAdapter creates a new instance of MockAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdapter {
	mock := &MockAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdapter is an autogenerated mock type for the Adapter type
type MockAdapter struct {
	mock.Mock
}

type MockAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdapter) EXPECT() *MockAdapter_Expecter {
	return &MockAdapter_Expecter{mock: &_m.Mock}
}

// HandleMessage provides a mock function for the type MockAdapter
func (_mock *MockAdapter) HandleMessage(ctx context.Context, message []byte) error {
	ret := _mock.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for HandleMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = returnFunc(ctx, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdapter_HandleMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleMessage'
type MockAdapter_HandleMessage_Call struct {
	*mock.Call
}

// HandleMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - message []byte
func (_e *MockAdapter_Expecter) HandleMessage(ctx interface{}, message interface{}) *MockAdapter_HandleMessage_Call {
	return &MockAdapter_HandleMessage_Call{Call: _e.mock.On("HandleMessage", ctx, message)}
}

func (_c *MockAdapter_HandleMessage_Call) Run(run func(ctx context.Context, message []byte)) *MockAdapter_HandleMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdapter_HandleMessage_Call) Return(err error) *MockAdapter_HandleMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdapter_HandleMessage_Call) RunAndReturn(run func(ctx context.Context, message []byte) error) *MockAdapter_HandleMessage_Call {
	_c.Call.Return(run)
	return _c
}
